# rebased/repackaged base image that only updates existing packages
FROM mbentley/alpine:latest
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

ARG JENKINS_VER
ARG JENKINS_URL
ARG BUILDX_VER

# install jenkins agent & dependencies
RUN apk add --no-cache bash bzip2 ca-certificates coreutils curl diffutils docker-cli fontconfig git gnupg jq less lynx musl-locales musl-locales-lang net-tools openjdk21-jre openssh-client parallel patch psmisc sudo tini ttf-dejavu tzdata unzip w3m wget xmlstarlet &&\
  mkdir /usr/share/jenkins &&\
  wget -nv -O /usr/share/jenkins/agent.jar "${JENKINS_URL}jnlpJars/agent.jar" &&\
  mkdir -p /var/lib/jenkins &&\
  chown -R 510:510 /var/lib/jenkins &&\
  for GROUP in 510 998 999; do delgroup "$(grep "x:${GROUP}:" /etc/group | awk -F ':' '{print $1}')" 2>/dev/null || true; done &&\
  addgroup -g 510 jenkins &&\
  addgroup -g 998 docker &&\
  addgroup -g 999 docker2 &&\
  adduser -D -u 510 -G jenkins -G docker -G docker2 -h /var/lib/jenkins jenkins &&\
  echo 'jenkins            ALL = (ALL) NOPASSWD: ALL' > /etc/sudoers.d/jenkinsnosudo &&\
  chmod 0440 /etc/sudoers.d/jenkinsnosudo &&\
  wget -q -O /tmp/docker-buildx "https://github.com/docker/buildx/releases/download/${BUILDX_VER}/buildx-${BUILDX_VER}.linux-amd64" &&\
  chmod +x /tmp/docker-buildx &&\
  mkdir -p /usr/libexec/docker/cli-plugins &&\
  mv /tmp/docker-buildx /usr/libexec/docker/cli-plugins/docker-buildx

# copy in entrypoint
COPY entrypoint.sh /entrypoint.sh

# drop from root to jenkins
USER jenkins

# JAVA_OPTS best practices come from https://support.cloudbees.com/hc/en-us/articles/222446987-Prepare-Jenkins-for-Support
ENV LANG=C.UTF-8 \
  JENKINS_HOME=/var/lib/jenkins \
  JAVA_OPTS="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+UnlockDiagnosticVMOptions -XX:+UseContainerSupport -Dorg.jenkinsci.plugins.pipeline.modeldefinition.parser.RuntimeASTTransformer.SCRIPT_SPLITTING_TRANSFORMATION=true" \
  MAX_MEMORY="4g"

VOLUME /var/lib/jenkins
ENTRYPOINT ["/entrypoint.sh"]
CMD ["jenkins-agent"]

