# rebased/repackaged base image that only updates existing packages
FROM mbentley/debian:bullseye
LABEL maintainer="Matt Bentley <mbentley@mbentley.net>"

ARG JENKINS_VER
ARG JENKINS_URL
ARG BUILDX_VER
ARG DEBIAN_FRONTEND=noninteractive

# install jenkins agent
RUN apt-get update &&\
  apt-get install --no-install-recommends -y bzip2 ca-certificates curl git-core gnupg jq less lynx openjdk-11-jre-headless openssh-client parallel patch psmisc sudo tini w3m wget xmlstarlet &\
  mkdir /usr/share/jenkins &&\
  wget -nv -O /usr/share/jenkins/agent.jar "${JENKINS_URL}jnlpJars/agent.jar" &&\
  mkdir -p /var/lib/jenkins &&\
  chown -R 510:510 /var/lib/jenkins &&\
  groupadd -g 510 jenkins &&\
  groupadd -g 998 docker &&\
  groupadd -g 999 docker2 &&\
  useradd -u 510 -g 510 -G docker,docker2 -d /var/lib/jenkins jenkins &&\
  echo 'jenkins            ALL = (ALL) NOPASSWD: ALL' > /etc/sudoers.d/jenkinsnosudo &&\
  chmod 0440 /etc/sudoers.d/jenkinsnosudo &&\
  rm -rf /var/lib/apt/lists/*


# install docker cli from the docker repos
RUN wget -q -O - https://download.docker.com/linux/debian/gpg | apt-key add - &&\
  echo "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable" > /etc/apt/sources.list.d/docker.list &&\
  apt-get update &&\
  apt-get install -y --no-install-recommends docker-ce-cli &&\
  rm -rf /var/lib/apt/lists/* &&\
  wget -q -O /tmp/docker-buildx "https://github.com/docker/buildx/releases/download/${BUILDX_VER}/buildx-${BUILDX_VER}.linux-amd64" &&\
  chmod +x /tmp/docker-buildx &&\
  mv /tmp/docker-buildx /usr/libexec/docker/cli-plugins/docker-buildx

# copy in entrypoint
COPY entrypoint.sh /entrypoint.sh

# drop from root to jenkins
USER jenkins

# JAVA_OPTS best practices come from https://support.cloudbees.com/hc/en-us/articles/222446987-Prepare-Jenkins-for-Support
ENV JENKINS_HOME=/var/lib/jenkins \
  JAVA_OPTS="-XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+UnlockDiagnosticVMOptions -XX:+UseContainerSupport -Dorg.jenkinsci.plugins.pipeline.modeldefinition.parser.RuntimeASTTransformer.SCRIPT_SPLITTING_TRANSFORMATION=true" \
  MAX_MEMORY="4g"

VOLUME /var/lib/jenkins
ENTRYPOINT ["/entrypoint.sh"]
CMD ["jenkins-agent"]
